/*
 * Automatically generated C config: don't edit
 */
#undef RTCONFIG_REALTEK
#undef RTCONFIG_RTL819X
#undef RTCONFIG_RTK_NAND
#define RTCONFIG_OPTIMIZE_SHARED_LIBS 1
#define RTCONFIG_L2TP 1
#define RTCONFIG_PPTP 1
#define RTCONFIG_EAPOL 1
#undef RTCONFIG_PPTPD
#undef RTCONFIG_ACCEL_PPTPD
#undef RTCONFIG_SNMPD
#define RTCONFIG_HTTPS 1
#undef RTCONFIG_BCMARM
#undef RTCONFIG_BCM7
#undef RTCONFIG_BCM_794
#undef RTCONFIG_BCM_7114
#undef RTCONFIG_BCM10
#undef RTCONFIG_BCM9
#undef RTCONFIG_BUILDBCM7
#undef RTCONFIG_ROMCFE
#undef RTCONFIG_ROMATECCODEFIX
#undef RTCONFIG_NV128
#define RTCONFIG_NVRAM_SIZE 0x8000
#undef RTCONFIG_DHDAP
#undef RTCONFIG_WLEXE
#undef RTCONFIG_DPSTA
#undef RTCONFIG_GMAC3
#undef RTCONFIG_BCMSMP
#undef RTCONFIG_BCMFA
#undef RTCONFIG_RGMII_BCM_FA
#undef RTCONFIG_5301X
#undef RTCONFIG_4352_5G
#define RTCONFIG_SSH 1
#undef RTCONFIG_CIFS
#undef RTCONFIG_BRCM_NAND_JFFS2
#define RTCONFIG_JFFS2 1
#undef RTCONFIG_DISKTEST
#undef RTCONFIG_JFFSV1
#undef RTCONFIG_ZEBRA
#undef RTCONFIG_QUAGGA
#define RTCONFIG_DDNS 1
#undef RTCONFIG_L7
#undef RTCONFIG_LZO
#undef RTCONFIG_IPSEC
#undef RTCONFIG_OPENSWAN
#undef RTCONFIG_QUICKSEC
#undef RTCONFIG_STRONGSWAN
#define RTCONFIG_IPV6 1
#define RTCONFIG_EBTABLES 1
#define RTCONFIG_EMF 1
#undef RTCONFIG_BCMBSD
#undef RTCONFIG_BCMSSD
#undef RTCONFIG_BCMDCS
#undef RTCONFIG_TOAD
#undef RTCONFIG_HSPOT
#undef RTCONFIG_FANCTRL
#undef RTCONFIG_BCMWL6
#undef RTCONFIG_WIRELESSWAN
#define RTCONFIG_WIRELESSREPEATER 1
#undef RTCONFIG_REPEATER
#undef RTCONFIG_DISABLE_REPEATER_UI
#undef RTCONFIG_PROXYSTA
#undef RTCONFIG_DISABLE_PROXYSTA_UI
#undef RTCONFIG_CONCURRENTREPEATER
#undef RTCONFIG_VHT80_80
#undef RTCONFIG_VHT160
#undef RTCONFIG_IXIAEP
#undef RTCONFIG_IPERF
#undef RTCONFIG_TCPDUMP
#define RTCONFIG_PARENTALCTRL 1
#undef RTCONFIG_YANDEXDNS
#undef RTCONFIG_DSL
#undef RTCONFIG_DSL_ANNEX_B
#undef RTCONFIG_DSL_TCLINUX
#undef RTCONFIG_VDSL
#undef RTCONFIG_DUALWAN
#undef RTCONFIG_HW_DUALWAN
#undef RTCONFIG_USER_LOW_RSSI
#undef RTCONFIG_NEW_USER_LOW_RSSI
#undef RTCONFIG_PUSH_EMAIL
#define RTCONFIG_USB 1
#undef RTCONFIG_USBRESET
#undef RTCONFIG_WIFIPWR
#undef RTCONFIG_XHCIMODE
#define RTCONFIG_MEDIA_SERVER 1
#undef RTCONFIG_LIMIT_MEDIA_SERVER
#undef RTCONFIG_CLOUDSYNC
#define RTCONFIG_FTP 1
#undef RTCONFIG_FTP_SSL
#undef RTCONFIG_WEBDAV
#define RTCONFIG_SAMBASRV 1
#define RTCONFIG_SAMBA3 1
#undef RTCONFIG_SAMBA36X
#define RTCONFIG_USB_EXTRAS 1
#undef RTCONFIG_TFAT
#define RTCONFIG_NTFS 1
#undef RTCONFIG_PARAGON_NTFS
#undef RTCONFIG_TUXERA_NTFS
#define RTCONFIG_OPEN_NTFS3G 1
#undef RTCONFIG_OPENPLUSPARAGON_NTFS
#undef RTCONFIG_OPENPLUSTUXERA_NTFS
#undef RTCONFIG_HFS
#undef RTCONFIG_DISK_MONITOR
#define RTCONFIG_USB_PRINTER 1
#define RTCONFIG_USB_MODEM 1
#undef RTCONFIG_USB_LESSMODEM
#define RTCONFIG_USB_MODEM_PIN 1
#undef RTCONFIG_USB_SMS_MODEM
#undef RTCONFIG_USB_BECEEM
#undef RTCONFIG_DYN_MODEM
#undef RTCONFIG_INTERNAL_GOBI
#undef RTCONFIG_BRCM_USBAP
#undef RTCONFIG_APP_PREINSTALLED
#define RTCONFIG_APP_NETINSTALLED 1
#define RTCONFIG_RALINK 1
#undef RTCONFIG_RALINK_RT3883
#undef RTCONFIG_RALINK_RT3052
#undef RTCONFIG_RALINK_MT7620
#define RTCONFIG_RALINK_MT7621 1
#undef RTCONFIG_RALINK_MT7628
#undef RTCONFIG_SPI_FAST_CLOCK
#undef RTCONFIG_EDCCA
#undef RTCONFIG_N56U_SR2
#undef RTCONFIG_AP_CARRIER_DETECTION
#define RTCONFIG_NEWSSID_REV2 1
#undef RTCONFIG_QCA
#undef RTCONFIG_NEW_APP_ARM
#undef RTCONFIG_QCA_ARM
#undef RTCONFIG_QCA953X
#undef RTCONFIG_QCA956X
#undef RTCONFIG_SOC_IPQ40XX
#undef RTCONFIG_FITFDT
#undef RTCONFIG_QCA_PLC_UTILS
#undef RTCONFIG_AR7420
#undef RTCONFIG_QCA7500
#undef RTCONFIG_QCA8033
#undef RTCONFIG_AIR_TIME_FAIRNESS
#undef RTCONFIG_POWER_SAVE
#undef RTCONFIG_DEFAULT_AP_MODE
#define RTCONFIG_ODMPID 1
#undef RTCONFIG_32BYTES_ODMPID
#undef RTCONFIG_TIMEMACHINE
#define RTCONFIG_MDNS 1
#define RTCONFIG_FINDASUS 1
#define RTCONFIG_REDIRECT_DNAME 1
#undef RTCONFIG_DHCP_OVERRIDE
#undef RTCONFIG_MTK_TW_AUTO_BAND4
#undef RTCONFIG_QCA_TW_AUTO_BAND4
#define RTCONFIG_LED_ALL 1
#undef RTCONFIG_COMA
#define CONFIG_LIBBCM 1
#define CONFIG_LIBUPNP 1
#define RTCONFIG_WPS 1
#undef RTCONFIG_WPS_ENROLLEE
#define RTCONFIG_SHP 1
#undef RTCONFIG_SFP
#undef RTCONFIG_STRACE
#undef RTCONFIG_4M_SFP
#undef RTCONFIG_8M_SFP
#undef RTCONFIG_16M_RAM_SFP
#undef RTCONFIG_GROCTRL
#undef RTCONFIG_LANWAN_LED
#undef RTCONFIG_WLAN_LED
#undef RTCONFIG_FAKE_ETLAN_LED
#undef RTCONFIG_EXT_LED_WPS
#undef RTCONFIG_SWMODE_SWITCH
#undef RTCONFIG_WL_AUTO_CHANNEL
#undef RTCONFIG_SMALL_FW_UPDATE
#undef RTCONFIG_WIRELESS_SWITCH
#undef RTCONFIG_WIFI_TOG_BTN
#undef RTCONFIG_WPS_RST_BTN
#undef RTCONFIG_WPS_ALLLED_BTN
#undef RTCONFIG_LOGO_LED
#undef RTCONFIG_LED_BTN
#undef RTCONFIG_USBEJECT
#define RTCONFIG_AUTODICT 1
#undef RTCONFIG_AUTOLIVEUPDATE_ZIP
#undef RTCONFIG_ISP_METER
#undef RTCONFIG_NVRAM_64K
#undef RTCONFIG_USB_XHCI
#undef RTCONFIG_WLMODULE_RT3090_AP
#undef RTCONFIG_WLMODULE_RT3352_INIC_MII
#undef RTCONFIG_WLMODULE_MT7610_AP
#define RTCONFIG_WLMODULE_RLT_WIFI 1
#define RTCONFIG_WLMODULE_MT7603E_AP 1
#undef RTCONFIG_WLMODULE_MT7628_AP
#undef RTCONFIG_WLMODULE_MT7615E_AP
#define RTCONFIG_PSISTLOG 1
#undef RTCONFIG_DUAL_TRX
#undef RTCONFIG_UBI
#undef RTCONFIG_UBIFS
#undef RTCONFIG_YAFFS
#undef RTCONFIG_OPTIMIZE_XBOX
#define RTCONFIG_NEW_REGULATION_DOMAIN 1
#undef RTCONFIG_DYN_DICT_NAME
#undef RTCONFIG_LAN4WAN_LED
#undef RTCONFIG_EXT4FS
#undef RTCONFIG_DMALLOC
#undef RTCONFIG_JFFS2ND_BACKUP
#define RTCONFIG_TEMPROOTFS 1
#undef RTCONFIG_ATEUSB3_FORCE
#undef RTCONFIG_JFFS2LOG
#undef RTCONFIG_WPSMULTIBAND
#undef RTCONFIG_RALINK_DFS
#undef RTCONFIG_ENGINEERING_MODE
#undef RTCONFIG_VPNC
#undef RTCONFIG_KYIVSTAR
#undef RTCONFIG_NO_WANPORT
#undef RTCONFIG_WANPORT2
#undef RTCONFIG_MULTIWAN_CFG
#undef RTCONFIG_ETRON_XHCI
#undef RTCONFIG_ETRON_XHCI_USB3_LED
#undef RTCONFIG_WPS_LED
#undef RTCONFIG_MMC_LED
#undef RTCONFIG_RESET_SWITCH
#undef RTCONFIG_WANRED_LED
#undef RTCONFIG_PWRRED_LED
#undef RTCONFIG_FAILOVER_LED
#undef RTCONFIG_SATA_LED
#undef RTCONFIG_BLINK_LED
#undef RTCONFIG_LEDS_CLASS
#undef RTCONFIG_EJUSB_BTN
#undef RTCONFIG_M2_SSD
#undef RTCONFIG_CFE_NVRAM_CHK
#undef RTCONFIG_DEBUG
#undef RTCONFIG_LLDP
#define RTCONFIG_HAS_5G 1
#undef RTCONFIG_TFTP
#undef RTCONFIG_QTN
#undef RTCONFIG_WPS_DUALBAND
#undef RTCONFIG_N18UTXBF
#undef RTCONFIG_BWDPI
#undef RTCONFIG_ADBLOCK
#undef RTCONFIG_TRAFFIC_LIMITER
#undef RTCONFIG_SPEEDTEST
#undef RTCONFIG_BONDING
#undef RTCONFIG_UIDEBUG
#undef RTCONFIG_ROG
#undef RTCONFIG_GEOIP
#undef RTCONFIG_TRANSMISSION
#undef RTCONFIG_NOWL
#define RTCONFIG_TCODE 1
#undef RTCONFIG_ALLNOWL
#undef RTCONFIG_WIFILOGO
#undef RTCONFIG_JFFS2USERICON
#undef RTCONFIG_EXT_RTL8365MB
#undef RTCONFIG_EXT_RTL8370MB
#undef RTCONFIG_TOR
#undef RTCONFIG_TR069
#undef RTCONFIG_TR181
#undef RTCONFIG_STAINFO
#undef RTCONFIG_CLOUDCHECK
#undef RTCONFIG_GETREALIP
#undef CONFIG_ASUS_APCLI_WPS
#undef RTCONFIG_TUNNEL
#undef RTCONFIG_CFEZ
#undef RTCONFIG_RESTRICT_GUI
#undef RTCONFIG_LACP
#undef RTCONFIG_KEY_GUARD
#undef RTCONFIG_RECVFILE
#undef RTCONFIG_WTFAST
#undef RTCONFIG_IFTTT
#undef RTCONFIG_ERP_TEST
#undef RTCONFIG_REBOOT_SCHEDULE
#undef RTCONFIG_CAPTIVE_PORTAL
#define RTCONFIG_UPNPC 1
#undef RTCONFIG_MULTICAST_IPTV
#define RTCONFIG_BONJOUR 1
#undef RTCONFIG_FBWIFI
#undef RTCONFIG_FORCE_AUTO_UPGRADE
#undef RTCONFIG_CHILLISPOT
#undef RTCONFIG_COOVACHILLI
#undef RTCONFIG_FREERADIUS
#undef RTCONFIG_TUXERA_SMBD
#undef RTCONFIG_BCMASPMD
#undef RTCONFIG_WLCLMLOAD
#undef RTCONFIG_MUMIMO
#undef RTCONFIG_NOTIFICATION_CENTER
#define RTCONFIG_PROTECTION_SERVER 1
#define RTCONFIG_6RELAYD 1
#undef RTCONFIG_PORT_BASED_VLAN
#undef RTCONFIG_DISABLE_NETWORKMAP
#undef RTCONFIG_WAN_AT_P4
#undef RTCONFIG_MTK_REP
#undef RTCONFIG_ATED122
#undef RTCONFIG_NOIPTV
#undef RTCONFIG_MTK_NAND
#undef RTCONFIG_RALINK_EDCCA
#define RTCONFIG_AUTOCOVER_SIP 1
#define RTCONFIG_DEFLAN50 1
#undef RTCONFIG_QAM256_2G
#undef RTCONFIG_MUMIMO_2G
#undef RTCONFIG_MUMIMO_5G
